name: 'Build Wheel'
description: 'Build wheel'

inputs:
  os:
    description: "OS to setup environment"
    required: true

runs:
  using: "composite"
  steps:
    - name: Build and test C++ Components
      if: ${{ inputs.os == 'Linux' }}
      shell: bash
      run: |
        CXX=$(which g++-14) ./scripts/build.sh
