from typing import Generic, TypeVar

LeftKeyType = TypeVar("LeftKeyType")
RightKeyType = TypeVar("RightKeyType")

class ManyToManyDict(Generic[LeftKeyType, RightKeyType]):
    def __init__(self) -> None: ...
    def add(self, left_key: LeftKeyType, right_key: RightKeyType) -> None: ...
    def remove(self, left_key: LeftKeyType, right_key: RightKeyType) -> None: ...
    def remove_left_key(self, left_key: LeftKeyType) -> set[RightKeyType]: ...
    def remove_right_key(self, right_key: RightKeyType) -> set[LeftKeyType]: ...
    def has_left_key(self, left_key: LeftKeyType) -> bool: ...
    def has_right_key(self, right_key: RightKeyType) -> bool: ...
    def has_key_pair(self, left_key: LeftKeyType, right_key: RightKeyType) -> bool: ...
    def get_left_items(self, right_key: RightKeyType) -> set[LeftKeyType]: ...
    def get_right_items(self, left_key: LeftKeyType) -> set[RightKeyType]: ...
    def left_keys(self) -> set[LeftKeyType]: ...
    def right_keys(self) -> set[RightKeyType]: ...
    def left_key_items(self) -> list[tuple[LeftKeyType, set[RightKeyType]]]: ...
    def right_key_items(self) -> list[tuple[RightKeyType, set[LeftKeyType]]]: ...
