from typing import Generic, Iterator, TypeVar

KeyType = TypeVar("KeyType")
ValueType = TypeVar("ValueType")

class OneToManyDict(Generic[KeyType, ValueType]):
    def __init__(self) -> None: ...
    def __contains__(self, item: object) -> bool: ...
    def __iter__(self) -> Iterator[KeyType]: ...
    def add(self, key: KeyType, value: ValueType) -> None: ...
    def has_key(self, key: KeyType) -> bool: ...
    def has_value(self, value: ValueType) -> bool: ...
    def get_key(self, value: ValueType) -> KeyType: ...
    def get_values(self, key: KeyType) -> set[ValueType]: ...
    def remove_key(self, key: KeyType) -> set[ValueType]: ...
    def remove_value(self, value: ValueType) -> KeyType: ...
    def keys(self) -> set[KeyType]: ...
    def values(self) -> list[set[ValueType]]: ...
    def items(self) -> list[tuple[KeyType, set[ValueType]]]: ...
