name: "3rd Party Libraries Compile"
description: "3rd Party Libraries Compile"

inputs:
  os:
    description: "operating system"
    required: true

runs:
  using: "composite"
  steps:
    - name: Cache Library Compile
      uses: actions/cache@v4
      id: compiled-libraries
      with:
        path: |
          thirdparties/compiled
        key: compiled-libraries-${{ inputs.os }}-${{ hashFiles('scripts/library_tool.*') }}

    - name: Compile Libraries (Linux)
      shell: bash
      if: (inputs.os == 'Linux') && (steps.compiled-libraries.outputs.cache-hit != 'true')
      run: |
        ./scripts/library_tool.sh capnp compile
        ./scripts/library_tool.sh libuv compile

    - name: Compile Libraries (Windows)
      shell: pwsh
      if: (inputs.os == 'Windows') && (steps.compiled-libraries.outputs.cache-hit != 'true')
      run: |
        ./scripts/library_tool.ps1 capnp compile
        ./scripts/library_tool.ps1 libuv compile
