from typing import Generic, Iterator, TypeVar

ItemType = TypeVar("ItemType")

class IndexedQueue(Generic[ItemType]):
    def __init__(self) -> None: ...
    def __contains__(self, item: object) -> bool: ...
    def __len__(self) -> int: ...
    def put(self, item: ItemType) -> None: ...
    def get(self) -> ItemType: ...
    def remove(self, item: ItemType) -> None: ...
    def to_list(self) -> list[ItemType]: ...
