from typing import Generic, TypeVar

PriorityType = TypeVar("PriorityType")
ItemType = TypeVar("ItemType")

class StablePriorityQueue(Generic[PriorityType, ItemType]):
    def __init__(self) -> None: ...
    def __contains__(self, item: object) -> bool: ...
    def __len__(self) -> int: ...
    def put(self, priority: PriorityType, item: ItemType) -> None: ...
    def get(self) -> tuple[PriorityType, ItemType]: ...
    def remove(self, item: ItemType) -> None: ...
    def decrease_priority(self, item: ItemType) -> None: ...
    def max_priority_item(self) -> tuple[PriorityType, ItemType]: ...
