name: Publish Python package to PyPI

on:
  release:
    types: [ created ]

permissions:
  contents: read

jobs:
  build:
    name: Build wheels (${{ matrix.os }}, ${{ matrix.cibw_archs }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cibw_archs: x86_64
          # TODO: re-enable after fixing QEMU exec format error
          # - os: ubuntu-latest
          #   cibw_archs: aarch64
          - os: windows-latest
            cibw_archs: AMD64
          - os: macos-latest
            cibw_archs: native
          - os: macos-15-intel
            cibw_archs: native
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up QEMU
        if: matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
        with:
          platforms: arm64

      - uses: ./.github/actions/setup-env
        with:
          os: ${{ runner.os }}
          python-version: '3.14'

      - uses: ./.github/actions/create-artifacts
        with:
          os: ${{ runner.os }}
        env:
          CIBW_ARCHS: ${{ matrix.cibw_archs }}
          CIBW_CONTAINER_ENGINE: "${{ matrix.cibw_archs == 'aarch64' && 'docker; create_args: --platform linux/arm64/v8' || 'docker' }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: dist-${{ matrix.os }}-${{ matrix.cibw_archs }}
          path: ./dist/

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          path: ./dist/
          pattern: dist-*
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: ./dist/
